---
- hosts: all
  become: true

  pre_tasks:
    - name: pre-tasks | update/upgrade package cache
      apt:
        update_cache: yes
        upgrade: dist
      changed_when: false
      when: ansible_distribution == "Debian"


- import_playbook: pve.yml
- import_playbook: dns.yml
- import_playbook: proxy.yml
- import_playbook: development.yml
  # - import_playbook: cmk.yml
  # - import_playbook: k8s.yml


- hosts: all
  become: true

  post_tasks:
    - name: post-tasks | cleanup package cache
      apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution == "Debian"

    - name: post-tasks | autoremove orphan packages
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution == "Debian"
