---
- name: install packages
  package:
    name: "{{ user_packages }}"

- name: create group
  group:
    name: "{{ user_user }}"
    state: present

- name: create user
  user:
    name: "{{ user_user }}"
    group: "{{ user_group }}"
    groups:
      - adm
      - sudo
    append: true
    state: present
    shell: /usr/bin/zsh

- name: ssh authorized key
  authorized_key:
    user: "{{ user_user }}"
    key: "{{ user_ssh_key}}"
    state: present

- name: /etc/sudoerd.d/adm
  template:
    src: sudo_adm.j2
    dest: /etc/sudoers.d/adm
    owner: root
    group: root
    mode: '0660'

- include_tasks: zsh.yml
